# Generated by Django 6.0.3 on 2026-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
