# Generated by Django 6.0.3 on 2026-03-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
